"""Run daily walk-forward research and track run-to-run changes."""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return default


def _run_walk_forward(args: argparse.Namespace) -> Dict[str, Any]:
    cmd = [
        sys.executable,
        "walk_forward_replay.py",
        "--window-hours",
        str(args.window_hours),
        "--windows",
        str(args.windows),
        "--auto-step-hours",
        args.auto_step_hours,
        "--recent-window-sec",
        str(args.recent_window_sec),
        "--min-score",
        str(args.min_score),
        "--min-margin",
        str(args.min_margin),
        "--dedup-sec",
        str(args.dedup_sec),
        "--min-confidence",
        str(args.min_confidence),
        "--min-trades-per-window",
        str(args.min_trades_per_window),
        "--min-active-windows",
        str(args.min_active_windows),
        "--max-runtime-sec",
        str(args.max_runtime_sec),
        "--ev-buffers",
        args.ev_buffers,
        "--ev-confidence-mults",
        args.ev_confidence_mults,
        "--ev-margin-mults",
        args.ev_margin_mults,
        "--ev-source-mults",
        args.ev_source_mults,
        "--ev-bearish-penalty-mults",
        args.ev_bearish_penalty_mults,
        "--ev-emergency-penalty-mults",
        args.ev_emergency_penalty_mults,
        "--ev-conflict-penalty-mults",
        args.ev_conflict_penalty_mults,
        "--top",
        str(args.top),
    ]
    if args.end_ts is not None:
        cmd.extend(["--end-ts", str(args.end_ts)])
    out = subprocess.check_output(cmd, text=True)
    return json.loads(out)


def _load_history(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        return []
    return data


def _save_history(path: Path, data: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def _save_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def _write_best_env(path: Path, params: Dict[str, Any]) -> None:
    mapping = {
        "ev_buffer_bps": "AGG_EV_BUFFER_BPS",
        "ev_confidence_mult": "AGG_EV_CONFIDENCE_MULT",
        "ev_margin_mult": "AGG_EV_MARGIN_MULT",
        "ev_source_mult": "AGG_EV_SOURCE_MULT",
        "ev_bearish_penalty_mult": "AGG_EV_BEARISH_PENALTY_MULT",
        "ev_emergency_penalty_mult": "AGG_EV_EMERGENCY_PENALTY_MULT",
        "ev_conflict_penalty_mult": "AGG_EV_CONFLICT_PENALTY_MULT",
    }
    lines: List[str] = [
        "# Auto-generated by daily_research.py",
        "# Copy selected values into your .env if needed.",
    ]
    for src_key, env_key in mapping.items():
        if src_key in params:
            lines.append(f"{env_key}={params[src_key]}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _should_promote(
    *,
    current: Dict[str, float],
    previous: Optional[Dict[str, float]],
    min_score_delta: float,
    max_drawdown_pct: float,
    promote_on_equal: bool,
) -> bool:
    # Always block promotion if current drawdown is above allowed ceiling.
    if current.get("avg_drawdown_pct", 0.0) > max_drawdown_pct:
        return False
    # If there is no previous run, allow baseline promotion.
    if previous is None:
        return True
    delta = current.get("score", -1e9) - previous.get("score", -1e9)
    if promote_on_equal:
        return delta >= 0.0
    return delta >= min_score_delta


def _extract_metrics(run: Dict[str, Any]) -> Dict[str, float]:
    best = run.get("best") or {}
    agg = best.get("aggregate") or {}
    return {
        "score": _safe_float(best.get("score"), -1e9),
        "avg_return_pct": _safe_float(agg.get("avg_return_pct"), 0.0),
        "avg_drawdown_pct": _safe_float(agg.get("avg_drawdown_pct"), 0.0),
        "avg_win_rate_pct": _safe_float(agg.get("avg_win_rate_pct"), 0.0),
        "avg_trades": _safe_float(agg.get("avg_trades"), 0.0),
        "profitable_windows_pct": _safe_float(agg.get("profitable_windows_pct"), 0.0),
    }


def _delta(current: Dict[str, float], prev: Dict[str, float]) -> Dict[str, float]:
    out: Dict[str, float] = {}
    for k, v in current.items():
        out[k] = v - _safe_float(prev.get(k), 0.0)
    return out


def _print_report(entry: Dict[str, Any], previous_entry: Optional[Dict[str, Any]]) -> None:
    current = entry["metrics"]
    prev = previous_entry["metrics"] if previous_entry else None
    print(f"[daily_research] run_at={entry['run_at']}")
    print(
        "[daily_research] "
        f"timed_out={entry['timed_out']} checked={entry['checked']} "
        f"selected_step_hours={entry['selected_step_hours']}"
    )
    print(
        "[daily_research] "
        f"score={current['score']:.4f} return={current['avg_return_pct']:.4f}% "
        f"drawdown={current['avg_drawdown_pct']:.4f}% "
        f"win_rate={current['avg_win_rate_pct']:.2f}%"
    )
    if not prev:
        print("[daily_research] baseline run (no previous history).")
        return
    d = _delta(current, prev)
    print(
        "[daily_research] delta_vs_prev "
        f"score={d['score']:+.4f} return={d['avg_return_pct']:+.4f}% "
        f"drawdown={d['avg_drawdown_pct']:+.4f}% "
        f"win_rate={d['avg_win_rate_pct']:+.2f}% "
        f"avg_trades={d['avg_trades']:+.2f}"
    )


def main() -> None:
    p = argparse.ArgumentParser(description="Daily WF research runner with history")
    p.add_argument("--history-path", type=str, default="reports/daily_research_history.json")
    p.add_argument("--latest-wf-path", type=str, default="reports/latest_wf.json")
    p.add_argument("--best-env-path", type=str, default="reports/best_params.env")
    p.add_argument("--promoted-env-path", type=str, default="reports/promoted_best.env")
    p.add_argument(
        "--promote-min-score-delta",
        type=float,
        default=0.2,
        help="Promote only if score improves by at least this delta vs previous run",
    )
    p.add_argument(
        "--promote-max-drawdown-pct",
        type=float,
        default=12.0,
        help="Promote only if avg_drawdown_pct is <= this threshold",
    )
    p.add_argument(
        "--promote-on-equal",
        action="store_true",
        help="If set, allow promotion when score is equal to previous run",
    )
    p.add_argument("--keep", type=int, default=30, help="How many latest runs to keep")
    p.add_argument("--end-ts", type=int, default=None)
    p.add_argument("--window-hours", type=int, default=720)
    p.add_argument("--windows", type=int, default=3)
    p.add_argument("--auto-step-hours", type=str, default="168,72,48,24,12")
    p.add_argument("--recent-window-sec", type=int, default=120)
    p.add_argument("--min-score", type=float, default=0.26)
    p.add_argument("--min-margin", type=float, default=0.08)
    p.add_argument("--dedup-sec", type=int, default=40)
    p.add_argument("--min-confidence", type=float, default=0.4)
    p.add_argument("--min-trades-per-window", type=int, default=20)
    p.add_argument("--min-active-windows", type=int, default=3)
    p.add_argument("--max-runtime-sec", type=int, default=1800)
    p.add_argument("--ev-buffers", type=str, default="8")
    p.add_argument("--ev-confidence-mults", type=str, default="18")
    p.add_argument("--ev-margin-mults", type=str, default="22")
    p.add_argument("--ev-source-mults", type=str, default="3")
    p.add_argument("--ev-bearish-penalty-mults", type=str, default="6")
    p.add_argument("--ev-emergency-penalty-mults", type=str, default="4")
    p.add_argument("--ev-conflict-penalty-mults", type=str, default="25")
    p.add_argument("--top", type=int, default=1)
    args = p.parse_args()

    history_path = Path(args.history_path)
    history = _load_history(history_path)
    prev_entry = history[-1] if history else None
    wf = _run_walk_forward(args)
    metrics = _extract_metrics(wf)
    best_params = ((wf.get("best") or {}).get("params") or {})

    entry = {
        "run_at": _now_iso(),
        "timed_out": bool(wf.get("timed_out", False)),
        "checked": int(wf.get("checked", 0) or 0),
        "selected_step_hours": int(wf.get("step_hours", 0) or 0),
        "metrics": metrics,
        "best_params": best_params,
    }
    history.append(entry)

    keep = max(1, int(args.keep))
    if len(history) > keep:
        history = history[-keep:]
    _save_history(history_path, history)
    _save_json(Path(args.latest_wf_path), wf)
    _write_best_env(Path(args.best_env_path), best_params)
    prev_metrics = prev_entry["metrics"] if prev_entry else None
    promoted = _should_promote(
        current=metrics,
        previous=prev_metrics,
        min_score_delta=float(args.promote_min_score_delta),
        max_drawdown_pct=float(args.promote_max_drawdown_pct),
        promote_on_equal=bool(args.promote_on_equal),
    )
    if promoted:
        _write_best_env(Path(args.promoted_env_path), best_params)
    _print_report(entry, prev_entry)
    print(
        "[daily_research] "
        f"promoted={promoted} promoted_env_path={args.promoted_env_path}"
    )


if __name__ == "__main__":
    main()
